server:
  port: 8080

spring:
  application:
    name: scada-server

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
      thread-name-prefix: scada-async-

